version: 2

models:
  - name: dim_host_listings
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric

  - name: dim_listings_cleansed
    description: cleansed listings dimensional table
    columns:
      - name: listing_id
        description: primary key of listings
        tests:
          - unique
          - not_null
      - name: host_id
        tests:
          - not_null
          - relationships:
              field: host_id
              to: ref('dim_hosts_cleansed')
      - name: room_type
        tests:
          - accepted_values:
              values:
                - 'Entire home/apt'
                - 'Private room'
                - 'Shared room'
                - 'Hotel room'
      - name: minimum_nights
        tests:
          - positive_value