version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
            - dbt_expectations.expect_column_distinct_count_to_equal:
                value: 4
      - name: reviews
        identifier: raw_reviews
        loaded_at_field:  date
        freshness: 
          error_after:
            count: 2
            period: day
          warn_after:
            count: 1
            period: day
      - name: hosts
        identifier: raw_hosts